### ISSUE TITLE
Scap DataBase

### ISSUE THREAD

**Issue by Nomadyb** [itiligent/Easy-OpenVAS-Builder#5]
![image](https://github.com/user-attachments/assets/d91b08ed-bb4b-43ba-9f2d-6b8c6ea48801)
Hi sir  I completed the installation on Ubuntu 22.04 LTS, but unfortunately, I am getting the error ‘The SCAP database is required.’ I have shared a screenshot of the feed statuses. What could be the cause?

**Comment by itiligent** [comment]
You need to wait quite a while after install for the database to build... when it is finished it will look like this, and from there you will be able to scan: 
![FeedStatus2](https://github.com/user-attachments/assets/6f18cc2a-8851-418f-b9e9-f76e4813bc17)
